const properStats = {
    school_name: 'School Name',
    wins: 'Wins',
    losses: 'Losses',
    win_loss_pct: 'Win-Loss Percentage',
    srs: 'Simple Rating System',
    sos: 'Strength of Schedule',
    wins_conf: 'Wins in Conference',
    losses_conf: 'Losses in Conference',
    wins_home: 'Wins at Home',
    losses_home: 'Losses at Home',
    wins_visitor: 'Wins as Visitor',
    losses_visitor: 'Losses as Visitor',
    pts: 'Points',
    opp_pts: 'Opponent Points',
    mp: 'Minutes Played',
    fg: 'Field Goals',
    fga: 'Field Goal Attempts',
    fg_pct: 'Field Goal Percentage',
    fg3: 'Three-Point Field Goals',
    fg3a: 'Three-Point Field Goal Attempts',
    fg3_pct: 'Three-Point Field Goal Percentage',
    ft: 'Free Throws',
    fta: 'Free Throw Attempts',
    ft_pct: 'Free Throw Percentage',
    orb: 'Offensive Rebounds',
    trb: 'Total Rebounds',
    ast: 'Assists',
    stl: 'Steals',
    blk: 'Blocks',
    tov: 'Turnovers',
    pf: 'Personal Fouls'
  };
  
  
module.exports = properStats;